apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ditry
spec:
  request: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1l6Q0NBVXNDQVFBd0hqRU9N
    QXdHQTFVRUF3d0ZaR2wwY25reEREQUtCZ05WQkFvTUEyUmxkakNDQVNJdwpEUVlKS29aSWh2Y05B
    UUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDdkNkNQMnYyR1dhc3BYNmQvSzJ1YVpWRDB4Ci83RjBD
    aTZoS3h5ZzNBYW5SV040VEdxYjZ0OWpteVk2Q1lsYXRTcmI0SkFZT3JKRVF2MjVmVlRvUldDVDlK
    OFEKVWFqUXU3SjV0TExaeW5HT3VOWmxLcGdBTEZ5ZXNBaG1zVDZmMS9hU0Nzd21yUHZFQmg3cUR1
    cGxLYVBpdzMvagpvRDlWRjZqeXRVYVl0Y0J4Q1Vsa3R0Z013UmwyNlhYS2o4VEVLdE5GYnhYUHJW
    WmJseTgxTjVHL3F1VUZnaGdxClhyVnZhbi9yaTVCQkZuc1cwZFpuZWxPMW5NZFJkR2FtbkJ4MTFu
    U1g4YWNTVGx6NGpQaXZVRjRDOWJqdXBRM28KNEFKMTIrRk9WbWFBKzArVTc4ZWcxbkVvMnNUUkMv
    eFdzWE9ldE83bUxIaHVzNmFnRGZBUFprNmw2bk1DQXdFQQpBYUFBTUEwR0NTcUdTSWIzRFFFQkN3
    VUFBNElCQVFDS1BrNlo5dnNvSmcrNW1PSWlIcXJieTA0VHdnbm5JdFBRClhGT1RuM3cwNnV6dEQ4
    QW4wUWtIVGZ0a09yd2hEclBtU2JNT2ZZaUhuVUc4bzV2c29ZQ2JBeXFvZXdoWnJTSjMKZVVSeSsr
    NXdOM0dOOE5ITXo1bXkrWEFSTGhKaUxKaEV3RUk1U1d6WXp0SVVLaFVHeU03QmRKU1lON3ljWlJB
    WQovM1NJelVwMTYwODRTcEVOZ3dUTVRZMVBBVk1lTlUvYWVLRmlCbUNLU0ZpdFVaNndGaXkyK1E3
    Ym54VUk5MGZBCjRTeEJ0WUZTcDQvVXgvaWtZbE9vM2NlMGkrZ3V5YkR3OUlxbkhYOVdsZEcxaDlk
    UE1RNmluUnh3bWtMb1lMY24KcVlPY2d6bndNU3E0V2JYZklEVTJrOXluTTQvRmJxYnlicXBXRk91
    Uk9nRVpVd0QyWG12TwotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # one day
  usages:
  - client auth
  - digital signature
  - key encipherment  