apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ditry-roles
  namespace: myns
subjects:
- kind: User
  name: ditry
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ditry-role
  apiGroup: rbac.authorization.k8s.io